#ifndef MEM_MAP_H_
#define MEM_MAP_H_

#define ADDR_ROM0_START (0x0000U)
#define ADDR_ROM0_END (0x3FFFU)
#define ROM0_SIZE (ADDR_ROM0_END - ADDR_ROM0_START)

#define ADDR_ROM1_START (0x4000U)
#define ADDR_ROM1_END (0x7FFFU)
#define ROM1_SIZE (ADDR_ROM1_END - ADDR_ROM1_START)

#define ADDR_VRAM_START (0x8000U)
#define ADDR_VRAM_END (0x9FFFU)
#define VRAM_SIZE (ADDR_VRAM_END - ADDR_VRAM_START)

#define ADDR_EXRAM_START (0xA000U)
#define ADDR_EXRAM_END (0xBFFFU)
#define EXRAM_SIZE (ADDR_EXRAM_END - ADDR_EXRAM_START)

#define ADDR_WRAM0_START (0xC000U)
#define ADDR_WRAM0_END (0xCFFFU)
#define WRAM0_SIZE (ADDR_WRAM0_END - ADDR_WRAM0_START)

#define ADDR_WRAM1_START (0xD000U)
#define ADDR_WRAM1_ECHO (0xDDFFU)
#define ADDR_WRAM1_END (0xDFFFU)
#define WRAM1_SIZE (ADDR_WRAM1_END - ADDR_WRAM1_START)

#define ADDR_LRAM_START (ADDR_VRAM_START)
#define ADDR_LRAM_END (ADDR_WRAM1_END)
#define LRAM_SIZE (ADDR_LRAM_END - ADDR_LRAM_START)

// Echo RAM (mirrors 0xC000 - 0xDDFF)
#define ADDR_ERAM_START (0xE000U)
#define ADDR_ERAM_END (0xFDFFU)
#define ERAM_SIZE (ADDR_ERAM_END - ADDR_ERAM_START)

// Object Attribute Memory
#define ADDR_OAM_START (0xFE00U)
#define ADDR_OAM_END (0xFE9FU)
#define OAM_SIZE (ADDR_OAM_END - ADDR_OAM_START)

// Not usable
#define ADDR_NU_START (0xFEA0U)
#define ADDR_NU_END (0xFEFFU)
#define NU_SIZE (ADDR_NU_END - ADDR_NU_START)

#define ADDR_IO_START (0xFF00U)
#define ADDR_IO_END (0xFF7FU)

#define ADDR_HRAM_START (0xFF80U)
#define ADDR_HRAM_END (0xFFFEU)
#define HRAM_SIZE (ADDR_HRAM_END - ADDR_HRAM_START)

#define ADDR_IE (0xFFFFU)
#define ADDR_IF (0xFF0FU)
// I/O registers
#define ADDR_JOYPAD (0xFF00U)

#define ADDR_SERIAL_START

#endif // MEM_MAP_H_